# syntax=docker/dockerfile:1.7
#
# Hermes Agent on Render.
#
# Extends the upstream NousResearch/hermes-agent image with:
#   - A permissions fix so the dashboard's Chat tab can rebuild at runtime
#   - A Caddy-based path multiplexer for Render's single exposed port
#     (dashboard + LINE webhook)
#   - A source-level patch enabling LINE DM pairing, plus a manager-
#     initiated one-off QR join invite (see patches/README.md)
#
# This image deliberately carries no Render account access (no MCP server,
# no API key, no `render` CLI). Provisioning/managing Render resources is
# an admin-only action taken outside the deployed agent, via the Render
# dashboard or CLI directly.
#
# Pin the upstream tag here. Bumping it is NOT a one-line change: follow
# UPGRADING.md, starting with `./scripts/upgrade-preflight.sh <new-tag>`.
# The last bump was done as a bare tag edit and ran wedged for 8 days.
ARG HERMES_IMAGE=docker.io/nousresearch/hermes-agent:v2026.7.20
ARG CADDY_IMAGE=docker.io/library/caddy:2.10-alpine
FROM ${CADDY_IMAGE} AS caddy
FROM ${HERMES_IMAGE}

# --- LINE DM pairing patch (plans/line-dm-pairing-plan.md, Phase 4) ---
# Upstream's LINE adapter drops unauthenticated DMs before they ever reach
# the gateway's central pairing logic (unlike WeCom/Weixin/QQBot/WhatsApp).
# This applies our fix directly to the pinned image's source via `git
# apply` (available in the base image; `patch` is not). The patch is
# generated by diffing against a clean checkout of the exact HERMES_IMAGE
# tag above — see patches/README.md before bumping that tag, since a patch
# generated against one tag is not guaranteed to apply against another.
USER root

# Basic vim for admin SSH debugging (repo CLAUDE.md's "Debugging a deployed
# instance over SSH" section) -- not present in the upstream base image.
# vim-tiny keeps the footprint small; swap for `vim` if you need full
# features (clipboard, python, etc). vim-tiny's postinst only registers
# alternatives for vi/view/ex/editor, not `vim` itself, so add that symlink
# by hand or `vim` comes back as "command not found".
RUN apt-get update \
    && apt-get install -y --no-install-recommends vim-tiny \
    && rm -rf /var/lib/apt/lists/* \
    && ln -s /usr/bin/vim.tiny /usr/bin/vim

# The mention-gate logic lives in an unpatched sibling module inside the LINE
# plugin package — a plain COPY, no `git apply` — so upstream drift can only
# break the ~20 lines of call-outs in line-group-mention.patch, and it breaks
# them loudly here at build time. Order matters: line-group-mention.patch is
# generated against a tree that already has line-dm-pairing.patch applied.
COPY modules/line/render_mention.py /opt/hermes/plugins/platforms/line/render_mention.py
COPY patches/line-dm-pairing.patch /tmp/line-dm-pairing.patch
COPY patches/line-group-mention.patch /tmp/line-group-mention.patch
RUN cd /opt/hermes && git apply -p1 --verbose /tmp/line-dm-pairing.patch \
     && git apply -p1 --verbose /tmp/line-group-mention.patch \
     && rm /tmp/line-dm-pairing.patch /tmp/line-group-mention.patch

# The dashboard runs as `hermes`, but ui-tui/ and node_modules/ still ship
# root-owned (upstream #20500). Without this the Chat tab's runtime esbuild
# rebuild fails with EACCES.
#
# The old `touch ink-bundle.js` / `touch entry.js` workarounds are gone as of
# v2026.7.7.2: _hermes_ink_bundle_stale() and _tui_build_needed() no longer
# exist, and the image now ships a prebuilt ui-tui/dist/entry.js, which
# hermes_cli/main.py treats as "the single runtime artefact" (prebuilt bundle
# mode). Nothing reads ink-bundle.js anymore.
#
# Re-verified against v2026.7.20: ui-tui/ and node_modules/ still ship
# root:root (so this chown is still load-bearing), dist/entry.js is still
# prebuilt, and neither function is back — `_tui_build_needed` survives only
# as a stale docstring mention in main.py, not as a definition.
RUN chown -R hermes:hermes /opt/hermes/ui-tui /opt/hermes/node_modules

# --- line-invite skill (plans/line-dm-pairing-plan.md, Phase 6c) ---
# Manager-initiated one-off LINE QR join invite, added without forking
# upstream (repo CLAUDE.md Pattern 3): the skill bundle is baked into the
# image, and a boot-time idempotent patcher (Pattern 1, via a cont-init
# hook — Pattern 2) registers it under skills.external_dirs on first boot,
# without ever overwriting an operator's own config.yaml edits.
#
# Per-instance business config (LINE_BASIC_ID, allowlists, API keys, etc.)
# is set post-deploy via admin-tools/env-sync — an admin-run CLI, outside
# this image, that upserts /opt/data/.env over SSH and verifies the gateway
# actually restarted. See admin-tools/env-sync/README.md.
COPY skills /opt/render-tools/skills-local
COPY scripts/patch-config.py /opt/render-tools/patch-config.py
COPY scripts/bootstrap.sh /etc/cont-init.d/03-render-tools
RUN chmod 0755 /opt/render-tools/patch-config.py /etc/cont-init.d/03-render-tools

# Path-based multiplexer for Render's single exposed port. Render routes
# only port 10000, but the LINE adapter's webhook server must be publicly
# reachable (LINE POSTs to it) AND the dashboard needs to stay usable.
# Caddy owns 10000 and fans out by path. Render publishes no other port, so
# the backends are unreachable from outside regardless of their bind host.
#
# The binary comes from the official Caddy image (static Go, no runtime
# deps) rather than a curl|tar of a GitHub release, so the version is
# pinned by CADDY_IMAGE and updates through the normal image flow.
#
# `cat` rather than a plain COPY to strip the binary's file capabilities.
# The official image ships caddy with cap_net_bind_service=ep, and the
# security.capability xattr survives COPY. Under a restrictive runtime
# (no-new-privileges, or a bounding set without that cap — Render is
# stricter than stock Docker here) exec'ing a file-capability binary as a
# non-root user fails with EPERM:
#
#   s6-applyuidgid: fatal: unable to exec caddy: Operation not permitted
#
# Caddy binds :10000, well above 1024, so it never needed the capability.
# Copying through `cat` creates a fresh inode with no xattrs. NOTE this
# reproduces only under such a runtime, not on stock `docker run`.
COPY --from=caddy /usr/bin/caddy /tmp/caddy.orig
RUN cat /tmp/caddy.orig > /usr/bin/caddy \
     && chmod 0755 /usr/bin/caddy \
     && rm /tmp/caddy.orig
COPY --chown=root:root caddy/Caddyfile /etc/caddy/Caddyfile
COPY --chown=root:root caddy/s6-rc.d/caddy /etc/s6-overlay/s6-rc.d/caddy
# Register with the `user` bundle, alongside upstream's dashboard and
# main-hermes services. An empty file named after the service is how s6-rc
# declares bundle membership.
RUN chmod 0755 /etc/s6-overlay/s6-rc.d/caddy/run /etc/s6-overlay/s6-rc.d/caddy/finish \
     && touch /etc/s6-overlay/s6-rc.d/user/contents.d/caddy \
     && install -d -o hermes -g hermes -m 0755 \
     /var/lib/caddy /var/lib/caddy/.config /var/lib/caddy/.local/share \
     && caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile

# Pre-create HERMES_HOME so chown works cleanly on first boot. The
# mounted disk replaces this empty dir at runtime; baking it just keeps
# the image self-contained for any non-disk use.
RUN install -d -o hermes -g hermes -m 0755 /opt/data

# Deliberately NO ENTRYPOINT override. The image's own ENTRYPOINT is
# ["/init", "/opt/hermes/docker/main-wrapper.sh"] (s6-overlay): /init runs
# the cont-init hooks as root, starts the supervised services (dashboard,
# per-profile gateways, caddy), then main-wrapper.sh runs this CMD and
# drops to the hermes user via s6-setuidgid.
#
# Overriding ENTRYPOINT here is what broke the v2026.5.7 → v2026.7.7.2
# upgrade: /usr/bin/tini had become a symlink to /init, so the old
# `tini -g -- bootstrap.sh` line resolved to `/init -g -- ...` and s6 tried
# to run `-g` as the main program (exit 127).
#
# As of v2026.7.20 /usr/bin/tini is no longer that symlink — it's a real
# shim script (upstream docker/tini-shim.sh) that forwards to /init. The
# lesson is unchanged and the reason is the point: what `tini` resolves to
# is upstream's business and has already been redefined twice. We don't
# depend on it either way, because we don't override ENTRYPOINT.
# Leave the image's own ENTRYPOINT alone; put boot work in
# /etc/cont-init.d/ instead.
CMD ["gateway", "run"]
